// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPoJl8RjuiEqvwP6RX0FOisPde-V5GSQ',
    appId: '1:218399398345:web:a0ae8370fd584813a4f018',
    messagingSenderId: '218399398345',
    projectId: 'geofotossociales',
    authDomain: 'geofotossociales.firebaseapp.com',
    storageBucket: 'geofotossociales.firebasestorage.app',
    measurementId: 'G-PPCNGJGGSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__FCHEJ2ZpgC2ROy3OkM46Eu6HFZMWts',
    appId: '1:218399398345:android:40c039f2ea00fe57a4f018',
    messagingSenderId: '218399398345',
    projectId: 'geofotossociales',
    storageBucket: 'geofotossociales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlJ6qUG_0m3vmQaSBdh6-BXaxUIgqmBNk',
    appId: '1:218399398345:ios:64ac38a4e17436c5a4f018',
    messagingSenderId: '218399398345',
    projectId: 'geofotossociales',
    storageBucket: 'geofotossociales.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlJ6qUG_0m3vmQaSBdh6-BXaxUIgqmBNk',
    appId: '1:218399398345:ios:64ac38a4e17436c5a4f018',
    messagingSenderId: '218399398345',
    projectId: 'geofotossociales',
    storageBucket: 'geofotossociales.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPoJl8RjuiEqvwP6RX0FOisPde-V5GSQ',
    appId: '1:218399398345:web:788bbca4e4e5ebfda4f018',
    messagingSenderId: '218399398345',
    projectId: 'geofotossociales',
    authDomain: 'geofotossociales.firebaseapp.com',
    storageBucket: 'geofotossociales.firebasestorage.app',
    measurementId: 'G-TCSRXTSCKW',
  );
}
